MODEL:
  META_ARCHITECTURE: "SimpleNet"
  BACKBONE:
    NAME: "build_efficientnet_backbone"
  EFFICIENT:
    OUT_FEATURES: ["block6"]
  SIMPLENET:
    IN_FEATURES: ["block6"]
    #NUM_CLASSES: ["family", "order", "species"]
    NUM_CLASSES: ["family", "species"]
DATASETS:
  TRAIN: ("herb_2021_4","herb_2021_5","herb_2021_8", "herb_2021_9")
  TEST: ("herb_2021_0",)
SOLVER:
  IMS_PER_BATCH: 64
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (80000, 100000)
  MAX_ITER: 130000
INPUT:
  MIN_SIZE_TRAIN: (240,280)
  MAX_SIZE_TRAIN: 400
  MIN_SIZE_TEST: 400
  CROP:
    SIZE: [0.8, 0.8]
VERSION: 2
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 1e-6
  NUM_WORKERS: 20
  ASPECT_RATIO_GROUPING: True